export enum Action{
  UPDATE_USERINFO = 'UPDATE_USERINFO',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  SHOW_GAME_TOP_POSITION = 'SHOW_GAME_TOP_POSITION',
  SHOW_MODAL = 'SHOW_MODAL',
  SEARCH_GAMES = 'SEARCH_GAMES',
  SEARCH_ALL_GAMES = 'SEARCH_ALL_GAMES',
  GAME_ID = 'GAME_ID',
  ABOUT_GAME = 'ABOUT_GAME',
  ADDED_GENRES_GAME = 'ADDED_GENRES_GAME',
  ADD_ALL_GENRES_GAMES = 'ADD_ALL_GENRES_GAMES'
}